# Generated by Django 5.0.7 on 2025-09-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Python file or app to audit', max_length=255)),
                ('file_author', models.CharField(blank=True, max_length=100, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Not Run', max_length=50)),
                ('report_path', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
