# Generated by Django 5.0.7 on 2025-09-15 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeauditreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codeauditreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
