# Generated by Django 5.0.7 on 2025-09-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_audit', '0002_codeauditreport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeauditreport',
            name='module_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codeauditreport',
            name='pylint_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
