# Generated by Django 5.0.7 on 2025-09-16 08:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_audit', '0003_codeauditreport_module_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAuditReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pylint_score', models.FloatField()),
                ('report_path', models.TextField()),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='code_audit.codeauditreport')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
    ]
