# Generated by Django 5.0.7 on 2025-09-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_audit', '0004_codeauditreportlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeauditreport',
            name='file_name',
            field=models.CharField(blank=True, help_text='Python file or app to audit', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='codeauditreport',
            name='module_name',
            field=models.CharField(help_text='filter module name', max_length=255),
        ),
        migrations.AlterField(
            model_name='codeauditreport',
            name='report_path',
            field=models.TextField(blank=True, default='/tmp/', null=True),
        ),
    ]
