# Generated by Django 5.0.7 on 2025-09-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_audit', '0005_alter_codeauditreport_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeauditreport',
            name='git_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
